image: "rust:latest"

test:cargo:
  script:
  - sudo apt-get install qemu-system
  - rustup default nightly-2019-05-07
  - rustup show
  - rustc --version && cargo --version
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cargo install cargo-xbuild
  - cargo install bootimage --version "^0.7.3"
  - cargo xtest