image: "rust:latest"

test:cargo:
  script:
  - rustup default nightly-2018-06-24
  - rustup show
  - rustc --version && cargo --version
  - rustup component add rust-src
  - apt-get update -yqq
  - apt-get install gcc grub-common make nasm -yqq
  - cargo install xargo
  - make iso
  - cargo test --all
